In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [14]:
""" 
dropna() gets rid of 90% of the rows, same with eq_data below
"""

eq_95_23 = pd.read_csv("data/earthquake_1995-2023.csv")
display(eq_95_23[:51])
display(eq_95_23[51:100])
display(eq_95_23[100:150])
display(eq_95_23[150:200])
display(eq_95_23[200:250])

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 6.5 - 42 km W of Sola, Vanuatu",6.5,16-08-2023 12:47,7,4,green,0,657,us,114,7.177000,25.0,mww,192.955,-13.8814,167.1580,"Sola, Vanuatu",NaN,Vanuatu
1,"M 6.5 - 43 km S of Intipucá, El Salvador",6.5,19-07-2023 00:22,8,6,yellow,0,775,us,92,0.679000,40.0,mww,69.727,12.8140,-88.1265,"Intipucá, El Salvador",NaN,NaN
2,"M 6.6 - 25 km ESE of Loncopué, Argentina",6.6,17-07-2023 03:05,7,5,green,0,899,us,70,1.634000,28.0,mww,171.371,-38.1911,-70.3731,"Loncopué, Argentina",South America,Argentina
3,"M 7.2 - 98 km S of Sand Point, Alaska",7.2,16-07-2023 06:48,6,6,green,1,860,us,173,0.907000,36.0,mww,32.571,54.3844,-160.6990,"Sand Point, Alaska",NaN,NaN
4,M 7.3 - Alaska Peninsula,7.3,16-07-2023 06:48,0,5,NaN,1,820,at,79,0.879451,172.8,Mi,21.000,54.4900,-160.7960,Alaska Peninsula,NaN,NaN
5,"M 6.6 - 277 km NNE of Codrington, Antigua and ...",6.6,10-07-2023 20:28,5,4,green,1,802,us,95,2.454000,37.0,mww,10.000,20.0196,-61.0955,"Codrington, Antigua and Barbuda",NaN,NaN
6,M 6.9 - Tonga,6.9,02-07-2023 10:27,4,4,green,1,741,us,136,1.179000,23.0,mww,229.000,-17.8530,-174.9370,Tonga,NaN,NaN
7,M 7.2 - south of the Fiji Islands,7.2,15-06-2023 18:06,8,6,green,1,804,us,85,2.590000,24.0,mww,167.404,-22.9824,-177.2080,the Fiji Islands,NaN,NaN
8,M 6.6 - Panama-Colombia border region,6.6,25-05-2023 03:05,6,6,green,1,733,us,50,2.163000,129.0,mww,10.000,8.8894,-77.1231,Panama-Colombia border region,NaN,Colombia
9,M 7.1 - southeast of the Loyalty Islands,7.1,20-05-2023 01:51,3,4,green,1,777,us,98,2.812000,56.0,mww,35.981,-23.0622,170.4560,the Loyalty Islands,NaN,NaN
10,M 7.7 - southeast of the Loyalty Islands,7.7,19-05-2023 02:57,5,4,green,1,927,us,277,3.111000,15.0,mww,18.027,-23.2286,170.6940,the Loyalty Islands,NaN,NaN
11,"M 7.6 - 95 km WNW of Hihifo, Tonga",7.6,10-05-2023 16:02,8,6,green,1,907,us,111,3.631000,17.0,mww,210.097,-15.6002,-174.6080,"Hihifo, Tonga",NaN,NaN
12,M 6.6 - south of the Fiji Islands,6.6,28-04-2023 03:13,0,2,green,0,670,us,52,5.123000,50.0,mww,598.467,-25.2657,178.4240,the Fiji Islands,NaN,NaN
13,"M 7.1 - 170 km SSE of Teluk Dalam, Indonesia",7.1,24-04-2023 20:00,9,7,green,0,838,us,70,2.282000,58.0,mww,15.462,-0.7810,98.5339,"Teluk Dalam, Indonesia",NaN,Indonesia
14,"M 7.1 - Kermadec Islands, New Zealand",7.1,24-04-2023 00:41,8,7,green,1,777,us,126,0.708000,23.0,mww,43.063,-30.0249,-177.8970,"Kermadec Islands, New Zealand",NaN,NaN
15,M 6.7 - south of the Fiji Islands,6.7,18-04-2023 04:31,0,3,green,1,691,us,166,4.719000,10.0,mww,595.854,-22.2844,179.3910,the Fiji Islands,NaN,NaN
16,"M 7.0 - 96 km N of Tuban, Indonesia",7.0,14-04-2023 09:55,5,3,green,0,818,us,131,1.881000,31.0,mww,594.028,-6.0255,112.0330,"Tuban, Indonesia",NaN,Indonesia
17,M 6.5 - near the east coast of the Kamchatka P...,6.5,03-04-2023 03:06,7,6,yellow,1,655,us,104,0.266000,30.0,mww,105.631,52.7772,158.4840,"the Kamchatka Peninsula, Russia",Asia,Russian Federation (the)
18,"M 7.0 - New Guinea, Papua New Guinea",7.0,02-04-2023 18:04,7,7,green,1,781,us,105,6.450000,31.0,mww,62.603,-4.2924,143.1550,"New Guinea, Papua New Guinea",Asia,Papua New Guinea
19,M 6.5 - 84 km NNW of San Antonio de los Cobres...,6.5,22-03-2023 16:00,4,4,green,0,656,us,97,1.622000,33.0,mww,209.976,-23.4797,-66.5108,"San Antonio de los Cobres, Argentina",South America,Argentina
20,"M 6.5 - 40 km SSE of Jurm, Afghanistan",6.5,21-03-2023 16:47,7,5,green,0,1350,us,134,2.530000,13.0,mww,187.589,36.5227,70.9787,"Jurm, Afghanistan",Asia,Afghanistan
21,M 6.8 - near the coast of Ecuador,6.8,18-03-2023 17:12,9,7,orange,1,1159,us,152,0.709000,28.0,mww,65.842,-2.8510,-79.8001,Ecuador,South America,Ecuador
22,M 7.0 - Kermadec Islands region,7.0,16-03-2023 00:56,8,5,green,1,756,us,116,1.789000,22.0,mww,22.065,-30.1147,-176.1120,Kermadec Islands region,NaN,NaN
23,"M 6.9 - Kermadec Islands, New Zealand",6.9,04-03-2023 06:41,5,5,green,1,735,us,108,0.784000,18.0,mww,205.681,-29.4748,-178.7870,"Kermadec Islands, New Zealand",NaN,NaN
24,"M 6.5 - 86 km WSW of Port-Olry, Vanuatu",6.5,02-03-2023 18:04,7,6,green,1,653,us,66,5.483000,45.0,mww,10.000,-15.3597,166.3850,"Port-Olry, Vanuatu",NaN,NaN
25,"M 6.5 - 108 km NW of Kimbe, Papua New Guinea",6.5,01-03-2023 05:36,4,2,green,1,652,us,115,2.739000,20.0,mww,598.925,-4.8138,149.4870,"Kimbe, Papua New Guinea",NaN,Papua New Guinea
26,"M 6.8 - 67 km W of Murghob, Tajikistan",6.8,23-02-2023 00:37,9,7,green,0,737,us,128,1.783000,20.0,mww,20.522,38.0726,73.2077,"Murghob, Tajikistan",Asia,Tajikistan
27,"M 7.5 - 4 km SSE of Ekinözü, Turkey",7.5,06-02-2023 10:24,9,9,orange,0,1411,us,135,0.850000,17.0,mww,10.000,38.0235,37.2030,"Ekinözü, Turkey",Asia,Turkiye
28,"M 6.7 - 18 km ESE of Nurdağı, Turkey",6.7,06-02-2023 01:28,9,8,yellow,0,800,us,108,0.218000,44.0,mww,14.497,37.4135,36.8306,"Nurdağı, Turkey",Asia,Turkiye
29,M 7.8 - Central Turkey,7.8,06-02-2023 01:17,9,9,red,0,2910,us,118,1.919000,32.0,mww,17.925,37.2012,36.9997,Central Turkey,Asia,Turkiye
30,M 6.8 -,6.8,20-01-2023 22:09,4,3,green,0,718,us,60,5.129000,61.0,mww,610.671,-26.7209,-63.0394,NaN,South America,Argentina
31,"M 7.0 - 153 km NW of Tobelo, Indonesia",7.0,18-01-2023 06:06,3,5,green,1,756,us,130,1.974000,17.0,mwc,28.566,2.7401,127.0510,"Tobelo, Indonesia",NaN,Indonesia
32,"M 7.6 - Pulau Pulau Tanimbar, Indonesia",7.6,09-01-2023 17:47,5,7,green,0,957,us,114,1.575000,21.0,mww,105.249,-7.0852,130.0390,"Pulau Pulau Tanimbar, Indonesia",NaN,Indonesia
33,M 7.0 - Vanuatu,7.0,08-01-2023 12:32,8,7,green,1,768,us,116,6.096000,36.0,mww,29.000,-14.9383,166.8780,Vanuatu,NaN,Vanuatu
34,"M 6.8 - 109 km NE of Hihifo, Tonga",6.8,04-12-2022 19:24,5,5,green,1,720,us,152,2.587000,26.0,mww,38.000,-15.3983,-172.9680,"Hihifo, Tonga",NaN,NaN
35,"M 7.0 - 18 km SW of Malango, Solomon Islands",7.0,22-11-2022 02:03,8,7,green,1,768,us,117,0.509000,17.0,mww,14.000,-9.7963,159.5960,"Malango, Solomon Islands",Oceania,Solomon Islands
36,"M 6.9 - 204 km SW of Bengkulu, Indonesia",6.9,18-11-2022 13:37,4,4,green,0,735,us,99,2.229000,34.0,mww,25.000,-4.9559,100.7380,"Bengkulu, Indonesia",NaN,NaN
37,M 7.0 -,7.0,12-11-2022 07:09,3,3,green,1,755,us,147,3.125000,18.0,mww,579.000,-20.0508,-178.3460,NaN,Oceania,Fiji
38,"M 7.3 - 205 km ESE of Neiafu, Tonga",7.3,11-11-2022 10:48,5,5,green,1,833,us,149,1.865000,21.0,mww,37.000,-19.2918,-172.1290,"Neiafu, Tonga",NaN,NaN
39,M 6.6 -,6.6,09-11-2022 10:14,0,2,green,1,670,us,131,4.998000,27.0,mww,624.464,-25.5948,178.2780,NaN,NaN,NaN
40,M 7.0 - south of the Fiji Islands,7.0,09-11-2022 09:51,4,3,green,1,755,us,142,4.578000,26.0,mwb,660.000,-26.0442,178.3810,the Fiji Islands,NaN,NaN
41,M 6.8 - south of the Fiji Islands,6.8,09-11-2022 09:38,1,3,green,1,711,us,136,4.678000,22.0,mww,630.379,-25.9678,178.3630,the Fiji Islands,NaN,NaN
42,"M 6.7 - 60 km SSW of Boca Chica, Panama",6.7,20-10-2022 11:57,7,6,green,1,797,us,145,1.151000,37.0,mww,20.000,7.6712,-82.3396,"Boca Chica, Panama",NaN,Panama
43,"M 6.8 - 55 km SSW of Aguililla, Mexico",6.8,22-09-2022 06:16,8,7,yellow,1,1179,us,175,2.137000,92.0,mww,20.000,18.3300,-102.9130,"Aguililla, Mexico",North America,Mexico
44,"M 7.6 - 35 km SSW of Aguililla, Mexico",7.6,19-09-2022 18:05,9,8,yellow,1,1799,us,271,1.153000,69.0,mww,26.943,18.3667,-103.2520,"Aguililla, Mexico",North America,Mexico
45,"M 6.9 - 90 km E of Yujing, Taiwan",6.9,18-09-2022 06:44,9,9,yellow,1,887,us,215,0.401000,34.0,mww,10.000,23.1444,121.3070,"Yujing, Taiwan",Asia,Taiwan
46,"M 6.5 - 96 km SE of Lugu, Taiwan",6.5,17-09-2022 13:41,7,7,green,1,756,us,178,0.430000,54.0,mww,10.000,23.0290,121.3480,"Lugu, Taiwan",Asia,Taiwan
47,"M 7.0 - 209 km SSE of Isangel, Vanuatu",7.0,14-09-2022 11:04,7,5,green,1,761,us,192,2.977000,45.0,mww,137.000,-21.2077,170.2390,"Isangel, Vanuatu",NaN,NaN
48,"M 7.6 - 70 km E of Kainantu, Papua New Guinea",7.6,10-09-2022 23:47,8,8,yellow,1,965,us,272,3.158000,12.0,mww,116.000,-6.2237,146.4710,"Kainantu, Papua New Guinea",Oceania,Papua New Guinea
49,"M 6.6 - 44 km SE of Kangding, China",6.6,05-09-2022 04:52,9,8,orange,0,1043,us,141,8.454000,34.0,mww,12.000,29.7263,102.2790,"Kangding, China",Asia,People's Republic of China
50,M 6.6 - south of the Kermadec Islands,6.6,14-08-2022 13:44,7,6,green,1,672,us,68,5.293000,34.0,mww,30.000,-32.6922,-178.9590,the Kermadec Islands,NaN,NaN

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
51,"M 7.0 - 11 km NE of Bantay, Philippines",7.0,27-07-2022 00:43,9,8,yellow,1,1351,us,152,5.276000,22.0,mww,33.729,17.5978,120.8090,"Bantay, Philippines",Asia,Philippines
52,"M 6.5 - 107 km SSW of Tarauacá, Brazil",6.5,08-06-2022 00:55,3,2,green,0,653,us,236,1.999000,31.0,mww,622.730,-9.0618,-71.1647,"Tarauacá, Brazil",South America,Brazil
53,"M 7.2 - 10 km W of Azángaro, Peru",7.2,26-05-2022 12:02,7,5,green,1,876,us,144,2.494000,40.0,mww,236.000,-14.8628,-70.3081,"Azángaro, Peru",South America,Peru
54,M 6.9 -,6.9,19-05-2022 10:13,2,5,green,1,733,us,127,0.371000,45.0,mww,10.000,-54.1325,159.0270,NaN,NaN,NaN
55,M 6.8 - 86 km NNW of San Antonio de los Cobres...,6.8,10-05-2022 23:06,6,5,green,1,762,us,162,1.505000,30.0,mww,220.000,-23.6141,-66.7236,"San Antonio de los Cobres, Argentina",South America,Argentina
56,"M 6.6 - 55 km WSW of Masachapa, Nicaragua",6.6,21-04-2022 07:42,6,5,green,1,762,us,0,0.914000,94.0,mww,27.000,11.5538,-86.9919,"Masachapa, Nicaragua",NaN,NaN
57,M 7.0 - southeast of the Loyalty Islands,7.0,31-03-2022 05:44,6,4,green,1,763,us,0,2.705000,26.0,mww,10.000,-22.5732,170.3490,the Loyalty Islands,NaN,NaN
58,"M 6.9 - 284 km ESE of Tadine, New Caledonia",6.9,30-03-2022 20:56,6,4,green,1,738,us,0,2.697000,42.0,mww,10.000,-22.7200,170.2770,"Tadine, New Caledonia",NaN,NaN
59,"M 6.7 - 65 km S of Hualien City, Taiwan",6.7,22-03-2022 17:41,8,7,green,1,806,us,0,0.289000,32.0,mww,24.000,23.3421,121.6360,"Hualien City, Taiwan",Asia,Taiwan
60,"M 7.3 - 57 km ENE of Namie, Japan",7.3,16-03-2022 14:36,9,8,red,1,2397,us,0,2.936000,29.0,mww,41.000,37.7015,141.5870,"Namie, Japan",NaN,NaN
61,"M 6.7 - 166 km W of Pariaman, Indonesia",6.7,13-03-2022 21:09,9,6,green,0,708,us,0,2.188000,43.0,mww,28.000,-0.6831,98.6034,"Pariaman, Indonesia",Asia,Indonesia
62,"M 6.6 - Kermadec Islands, New Zealand",6.6,02-03-2022 12:52,2,7,green,1,670,us,0,0.827000,46.0,mww,24.000,-30.0528,-177.7400,"Kermadec Islands, New Zealand",NaN,NaN
63,M 6.8 - south of the Fiji Islands,6.8,16-02-2022 20:21,2,3,green,1,712,us,0,5.780000,12.0,mww,535.000,-23.7852,-179.9680,the Fiji Islands,NaN,NaN
64,"M 6.5 - 49 km NW of Barranca, Peru",6.5,03-02-2022 15:58,8,6,green,0,690,us,0,3.026000,22.0,mww,110.000,-4.4550,-76.9395,"Barranca, Peru",South America,Peru
65,M 6.5 - Kermadec Islands region,6.5,29-01-2022 02:46,7,4,green,1,651,us,0,1.088000,57.0,mww,8.000,-29.5350,-176.7290,Kermadec Islands region,NaN,NaN
66,"M 6.6 - 80 km SW of Labuan, Indonesia",6.6,14-01-2022 09:05,8,6,green,0,785,us,0,2.418000,22.0,mww,33.000,-6.9291,105.2510,"Labuan, Indonesia",NaN,Indonesia
67,"M 6.5 - 71 km SE of Nikolski, Alaska",6.5,11-01-2022 12:39,0,3,NaN,1,650,at,97,1.616070,108.0,Mi,37.000,52.5020,-168.0800,"Nikolski, Alaska",NaN,NaN
68,"M 6.5 - 71 km SE of Nikolski, Alaska",6.5,11-01-2022 12:39,0,3,NaN,1,650,pt,23,0.000000,208.8,Mi,37.000,52.5020,-168.0800,"Nikolski, Alaska",NaN,NaN
69,"M 6.6 - 53 km SE of Nikolski, Alaska",6.6,11-01-2022 12:39,8,5,green,1,674,us,0,0.507000,49.0,mww,19.000,52.6252,-168.1500,"Nikolski, Alaska",NaN,NaN
70,"M 6.7 - 91 km SE of Nikolski, Alaska",6.7,11-01-2022 11:35,0,4,NaN,1,691,at,50,0.936943,126.0,Mi,33.000,52.4800,-167.7360,"Nikolski, Alaska",NaN,NaN
71,"M 6.7 - 91 km SE of Nikolski, Alaska",6.7,11-01-2022 11:35,0,4,NaN,1,691,pt,20,0.000000,205.2,Mi,33.000,52.4800,-167.7360,"Nikolski, Alaska",NaN,NaN
72,"M 6.8 - 100 km SE of Nikolski, Alaska",6.8,11-01-2022 11:35,7,6,green,1,730,us,0,0.920000,61.0,mww,20.000,52.6563,-167.9170,"Nikolski, Alaska",NaN,NaN
73,"M 6.6 - 48 km WNW of Pólis, Cyprus",6.6,11-01-2022 01:07,6,6,green,0,976,us,0,1.168000,21.0,mww,21.000,35.1456,31.9095,"Pólis, Cyprus",Asia,NaN
74,"M 6.6 - northern Qinghai, China",6.6,07-01-2022 17:45,9,8,orange,0,1012,us,0,2.685000,13.0,mww,13.000,37.8167,101.2990,"northern Qinghai, China",Asia,People's Republic of China
75,"M 7.3 - 125 km NNE of Lospalos, Timor Leste",7.3,29-12-2021 18:25,8,7,green,0,921,us,0,3.713000,19.0,mww,165.490,-7.5924,127.5810,"Lospalos, Timor Leste",NaN,Indonesia
76,M 7.3 - Flores Sea,7.3,14-12-2021 03:20,9,5,green,1,854,us,0,1.025000,32.0,mww,14.270,-7.6033,122.2000,Flores Sea,Asia,Indonesia
77,"M 7.5 - 43 km NNW of Barranca, Peru",7.5,28-11-2021 10:52,8,8,yellow,1,1094,us,0,4.951000,40.0,mww,126.000,-4.4898,-76.8461,"Barranca, Peru",South America,Peru
78,"M 6.6 - 177 km SE of Hirara, Japan",6.6,10-11-2021 15:45,7,4,green,1,688,us,0,3.259000,15.0,mww,12.000,23.5414,126.4800,"Hirara, Japan",NaN,NaN
79,"M 6.9 - 112 km E of Chignik, Alaska",6.9,11-10-2021 09:10,8,6,green,1,995,ak,0,0.000000,0.0,mww,51.600,56.2581,-156.4920,"Chignik, Alaska",North America,United States of America
80,M 6.9 - Vanuatu region,6.9,09-10-2021 10:58,4,3,green,1,740,us,0,4.778000,31.0,mww,535.000,-21.1704,174.5400,Vanuatu region,NaN,NaN
81,M 7.3 - Vanuatu region,7.3,02-10-2021 06:29,4,4,green,1,826,us,0,4.493000,32.0,mww,527.000,-21.1036,174.8950,Vanuatu region,NaN,NaN
82,"M 6.5 - 80 km SW of Jiquilillo, Nicaragua",6.5,22-09-2021 09:57,7,5,green,1,684,us,0,0.993000,114.0,mww,21.000,12.1598,-87.8542,"Jiquilillo, Nicaragua",NaN,NaN
83,"M 7.0 - Acapulco, Mexico",7.0,08-09-2021 01:47,8,8,red,1,2504,us,0,0.070000,43.0,mww,20.000,16.9502,-99.7877,"Acapulco, Mexico",North America,Mexico
84,M 7.1 - South Sandwich Islands region,7.1,22-08-2021 21:33,1,4,green,1,776,us,0,9.799000,32.0,mww,6.000,-60.3026,-24.9992,South Sandwich Islands region,NaN,Antarctica
85,M 6.6 - South Sandwich Islands region,6.6,22-08-2021 00:45,1,3,green,1,670,us,0,8.865000,19.0,mww,7.000,-60.1023,-24.4608,South Sandwich Islands region,NaN,Antarctica
86,"M 6.9 - 17 km N of Port-Olry, Vanuatu",6.9,18-08-2021 10:10,8,7,green,1,741,us,0,0.579000,54.0,mww,93.000,-14.8920,167.0850,"Port-Olry, Vanuatu",Oceania,Vanuatu
87,M 6.9 - South Sandwich Islands region,6.9,16-08-2021 11:10,6,4,green,1,734,us,0,8.363000,48.0,mww,16.700,-58.3814,-23.3318,South Sandwich Islands region,NaN,NaN
88,"M 7.2 - Nippes, Haiti",7.2,14-08-2021 12:29,9,8,red,1,2331,us,0,1.178000,23.0,mww,10.000,18.3521,-73.4804,"Nippes, Haiti",North America,Haiti
89,"M 6.9 - 136 km SE of Perryville, Alaska",6.9,14-08-2021 11:57,5,4,green,1,738,ak,0,0.000000,0.0,mww,33.300,55.2364,-157.7070,"Perryville, Alaska",NaN,NaN
90,"M 6.9 - 125 km SE of Perryville, Alaska",6.9,14-08-2021 11:57,5,4,green,1,738,us,0,1.173000,36.0,mww,20.740,55.2657,-157.6800,"Perryville, Alaska",NaN,NaN
91,M 8.1 - South Sandwich Islands region,8.1,12-08-2021 18:35,0,7,green,0,1009,us,0,7.463000,78.0,mww,22.790,-58.4157,-25.3206,South Sandwich Islands region,NaN,NaN
92,M 7.5 - South Sandwich Islands region,7.5,12-08-2021 18:32,9,6,green,1,868,us,0,7.227000,38.0,mww,47.230,-57.5959,-25.1874,South Sandwich Islands region,NaN,NaN
93,"M 7.1 - 60 km ENE of Pondaguitan, Philippines",7.1,11-08-2021 17:46,9,7,green,1,846,us,0,1.273000,25.0,mww,55.140,6.4547,126.7420,"Pondaguitan, Philippines",NaN,NaN
94,"M 8.2 - 91 km ESE of Perryville, Alaska",8.2,29-07-2021 06:15,8,6,green,1,1237,us,0,0.875000,66.0,mww,46.660,55.4742,-157.9170,"Perryville, Alaska",NaN,NaN
95,"M 8.2 - 99 km SE of Perryville, Alaska",8.2,29-07-2021 06:15,8,7,yellow,1,1252,ak,0,0.000000,0.0,mww,35.000,55.3154,-157.8290,"Perryville, Alaska",NaN,NaN
96,"M 6.7 - 15 km S of Hukay, Philippines",6.7,23-07-2021 20:48,8,5,green,1,935,us,0,8.139000,12.0,mww,110.000,13.6989,120.7130,"Hukay, Philippines",Asia,Philippines
97,"M 6.7 - 71 km S of Burica, Panama",6.7,21-07-2021 21:15,6,6,green,1,830,us,0,1.395000,61.0,mww,10.000,7.5904,-82.8813,"Burica, Panama",NaN,NaN
98,"M 6.5 - Kermadec Islands, New Zealand",6.5,20-06-2021 17:05,0,4,green,1,650,us,0,7.994000,24.0,mww,25.000,-30.2144,-177.7730,"Kermadec Islands, New Zealand",NaN,NaN
99,"M 6.5 - 265 km SSE of Alo, Wallis and Futuna",6.5,21-05-2021 22:13,5,7,green,1,652,us,0,4.518000,44.0,mww,10.000,-16.4796,-177.3560,"Alo, Wallis and Futuna",NaN,NaN

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
100,"M 7.3 - Southern Qinghai, China",7.3,21-05-2021 18:04,9,9,orange,0,1025,us,0,4.655,9.00,mww,10.00,34.5861,98.2551,"Southern Qinghai, China",Asia,People's Republic of China
101,"M 6.7 - 260 km S of Sinabang, Indonesia",6.7,14-05-2021 06:33,8,4,green,0,698,us,0,1.487,37.00,mww,11.00,0.1684,96.6475,"Sinabang, Indonesia",NaN,NaN
102,M 6.7 - Mauritius - Reunion region,6.7,12-05-2021 14:05,9,3,green,0,694,us,0,10.669,45.00,mww,10.00,-17.2495,66.3745,Mauritius - Reunion region,NaN,NaN
103,M 6.9 -,6.9,01-05-2021 01:27,7,6,green,1,919,us,0,2.619,35.00,mww,43.00,38.2296,141.6650,NaN,Asia,Japan
104,"M 6.5 - 207 km WSW of Haveluloto, Tonga",6.5,25-04-2021 22:28,4,4,green,0,651,us,0,5.931,20.00,mww,246.00,-21.6857,-177.0640,"Haveluloto, Tonga",NaN,NaN
105,"M 6.5 - 225 km WNW of Pangai, Tonga",6.5,24-04-2021 00:23,6,4,green,0,652,us,0,10.405,19.00,mww,301.00,-18.9204,-176.2350,"Pangai, Tonga",NaN,NaN
106,"M 7.0 - 30 km E of Ishinomaki, Japan",7.0,20-03-2021 09:09,7,7,yellow,1,1052,us,0,2.378,35.00,mww,43.00,38.4752,141.6070,"Ishinomaki, Japan",Asia,Japan
107,"M 6.6 - 171 km SSE of Ust’-Kamchatsk Staryy, R...",6.6,16-03-2021 18:38,5,5,green,1,672,us,0,3.183,18.00,mww,13.23,54.7018,163.2080,"Ust’-Kamchatsk Staryy, Russia",NaN,NaN
108,M 6.5 - Kermadec Islands region,6.5,04-03-2021 23:12,0,4,green,0,650,us,0,11.764,25.00,mwb,24.00,-28.4792,-176.6190,Kermadec Islands region,NaN,NaN
109,"M 8.1 - Kermadec Islands, New Zealand",8.1,04-03-2021 19:28,9,8,green,1,1021,us,0,0.739,21.00,mww,28.93,-29.7466,-177.2240,"Kermadec Islands, New Zealand",NaN,NaN
110,"M 7.4 - Kermadec Islands, New Zealand",7.4,04-03-2021 17:41,3,7,green,1,843,us,0,0.437,30.00,mww,43.00,-29.6131,-177.8420,"Kermadec Islands, New Zealand",NaN,NaN
111,"M 7.3 - 182 km NE of Gisborne, New Zealand",7.3,04-03-2021 13:27,7,6,green,1,932,us,0,0.918,24.00,mww,10.00,-37.5960,179.5440,"Gisborne, New Zealand",NaN,NaN
112,"M 7.1 - 73 km ENE of Namie, Japan",7.1,13-02-2021 14:07,9,8,orange,1,1612,us,0,3.085,11.00,mww,43.98,37.6856,141.9920,"Namie, Japan",NaN,NaN
113,M 7.7 - southeast of the Loyalty Islands,7.7,10-02-2021 13:19,9,4,green,1,918,us,0,7.989,15.00,mww,10.00,-23.2787,171.4890,the Loyalty Islands,NaN,NaN
114,M 6.9 - South Shetland Islands,6.9,23-01-2021 23:36,9,5,green,1,739,us,0,1.550,16.00,mww,15.00,-61.8484,-55.5590,South Shetland Islands,NaN,Antarctica
115,"M 7.0 - 211 km SE of Pondaguitan, Philippines",7.0,21-01-2021 12:23,7,5,green,1,802,us,0,2.821,15.00,mww,80.00,5.0074,127.5170,"Pondaguitan, Philippines",NaN,NaN
116,"M 6.7 - 29 km SSW of Turt, Mongolia",6.7,11-01-2021 21:32,8,8,green,0,776,us,0,2.043,22.00,mww,10.00,51.2407,100.4430,"Turt, Mongolia",Asia,Mongolia
117,"M 6.7 - 146 km WNW of Corral, Chile",6.7,27-12-2020 21:39,5,5,green,1,776,us,0,1.319,19.00,mww,10.00,-39.3264,-74.9067,"Corral, Chile",NaN,NaN
118,"M 7.0 - 13 km NNE of Néon Karlovásion, Greece",7.0,30-10-2020 11:51,8,7,orange,0,1527,us,0,1.518,18.00,mww,21.00,37.8973,26.7953,"Néon Karlovásion, Greece",Europe,Greece
119,"M 7.6 - 99 km SE of Sand Point, Alaska",7.6,19-10-2020 20:54,9,7,yellow,1,1165,us,0,0.230,36.00,mww,28.37,54.6620,-159.6750,"Sand Point, Alaska",North America,United States of America
120,M 6.9 - central Mid-Atlantic Ridge,6.9,18-09-2020 21:43,0,3,green,1,732,us,0,11.255,16.00,mww,10.00,0.9604,-26.8332,central Mid-Atlantic Ridge,NaN,NaN
121,"M 6.5 - 94 km NW of Vallenar, Chile",6.5,01-09-2020 21:09,6,6,green,0,674,us,0,0.388,49.00,mww,16.00,-27.9285,-71.3937,"Vallenar, Chile",NaN,NaN
122,"M 6.8 - 86 km NW of Vallenar, Chile",6.8,01-09-2020 04:09,6,7,green,1,824,us,0,0.312,69.00,mww,21.00,-28.0130,-71.1958,"Vallenar, Chile",NaN,Chile
123,M 6.5 - central Mid-Atlantic Ridge,6.5,30-08-2020 21:20,4,5,green,0,651,us,0,15.394,31.00,mww,10.00,0.8696,-29.7046,central Mid-Atlantic Ridge,NaN,NaN
124,"M 6.9 - 222 km SSE of Katabu, Indonesia",6.9,21-08-2020 04:09,4,3,green,0,749,us,0,2.267,20.00,mww,624.00,-6.6704,123.4930,"Katabu, Indonesia",NaN,Indonesia
125,"M 6.9 - 122 km WSW of Bengkulu, Indonesia",6.9,18-08-2020 22:29,4,4,green,0,735,us,0,1.716,25.00,mww,26.00,-4.2791,101.2150,"Bengkulu, Indonesia",NaN,Indonesia
126,"M 6.8 - 138 km WSW of Bengkulu, Indonesia",6.8,18-08-2020 22:23,5,4,green,0,716,us,0,1.816,34.00,mww,22.00,-4.3724,101.0950,"Bengkulu, Indonesia",NaN,Indonesia
127,"M 6.6 - 13 km E of San Pedro, Philippines",6.6,18-08-2020 00:03,9,8,yellow,1,784,us,0,5.128,14.00,mww,10.00,12.0065,124.1300,"San Pedro, Philippines",NaN,Philippines
128,"M 7.8 - 99 km SSE of Perryville, Alaska",7.8,22-07-2020 06:12,9,7,green,1,1111,us,0,0.621,60.00,mww,28.00,55.1079,-158.4770,"Perryville, Alaska",NaN,NaN
129,"M 7.0 - 114 km NNW of Popondetta, Papua New Gu...",7.0,17-07-2020 02:50,6,7,green,1,820,us,0,1.671,18.00,mww,73.00,-7.8470,147.7550,"Popondetta, Papua New Guinea",NaN,Papua New Guinea
130,"M 6.6 - 97 km N of Batang, Indonesia",6.6,06-07-2020 22:54,4,2,green,0,684,us,0,1.458,14.00,mww,533.76,-5.6368,110.6780,"Batang, Indonesia",NaN,Indonesia
131,"M 7.4 - 9 km SE of Santa María Xadani, Mexico",7.4,23-06-2020 15:29,8,8,orange,1,1494,us,0,0.151,30.00,mww,20.00,15.9163,-95.9533,"Santa María Xadani, Mexico",North America,Mexico
132,M 7.4 - south of the Kermadec Islands,7.4,18-06-2020 12:49,7,7,green,1,873,us,0,4.035,23.00,mww,10.00,-33.2938,-177.8380,the Kermadec Islands,NaN,NaN
133,"M 6.6 - 130 km WNW of Naze, Japan",6.6,13-06-2020 15:51,5,4,green,1,734,us,0,2.015,18.00,mww,165.00,28.9386,128.2620,"Naze, Japan",NaN,NaN
134,"M 6.8 - 48 km SW of San Pedro de Atacama, Chile",6.8,03-06-2020 07:35,6,6,green,1,835,us,0,1.164,21.00,mww,112.00,-23.2966,-68.4204,"San Pedro de Atacama, Chile",South America,Chile
135,"M 6.5 - Monte Cristo Range, NV Earthquake",6.5,15-05-2020 11:03,7,8,green,0,1320,nn,27,0.357,55.79,ml,2.70,38.1689,-117.8500,"Monte Cristo Range, NV Earthquake",North America,United States of America
136,"M 6.6 - 175 km SSE of Lata, Solomon Islands",6.6,12-05-2020 22:41,4,6,green,1,671,us,0,3.403,12.00,mww,107.00,-12.0662,166.6480,"Lata, Solomon Islands",NaN,NaN
137,M 6.8 - Banda Sea,6.8,06-05-2020 13:53,4,6,green,0,738,us,0,1.921,16.00,mww,96.00,-6.7762,129.7850,Banda Sea,NaN,Indonesia
138,"M 6.5 - 91 km S of Néa Anatolí, Greece",6.5,02-05-2020 12:51,7,6,green,0,678,us,0,1.293,19.00,mww,10.00,34.1818,25.7101,"Néa Anatolí, Greece",NaN,NaN
139,"M 6.5 - Stanley, Idaho",6.5,31-03-2020 23:52,8,8,green,0,1410,us,0,0.885,31.00,mww,12.06,44.4646,-115.1180,"Stanley, Idaho",North America,United States of America
140,"M 7.5 - 221 km SSE of Severo-Kuril’sk, Russia",7.5,25-03-2020 02:49,6,5,green,1,879,us,0,4.109,12.00,mww,57.80,48.9638,157.6950,"Severo-Kuril’sk, Russia",NaN,NaN
141,"M 7.0 - 95 km ENE of Kuril’sk, Russia",7.0,13-02-2020 10:33,5,6,yellow,1,770,us,0,4.501,25.00,mww,143.00,45.6161,148.9590,"Kuril’sk, Russia",Asia,Russia
142,"M 7.7 - 123 km NNW of Lucea, Jamaica",7.7,28-01-2020 19:10,9,6,yellow,1,1812,us,0,1.657,26.00,mww,14.86,19.4193,-78.7560,"Lucea, Jamaica",NaN,NaN
143,"M 6.7 - 13 km N of Do?anyol, Turkey",6.7,24-01-2020 17:55,8,9,orange,0,1247,us,0,0.870,49.00,mww,10.00,38.4312,39.0609,"Do?anyol, Turkey",Asia,Turkey
144,"M 6.8 - 7 km S of Magsaysay, Philippines",6.8,15-12-2019 06:11,9,7,yellow,1,825,us,0,0.546,39.00,mww,18.00,6.6969,125.1740,"Magsaysay, Philippines",NaN,Philippines
145,"M 7.1 - 138km E of Bitung, Indonesia",7.1,14-11-2019 16:17,6,6,green,1,799,us,0,1.271,11.00,mww,33.00,1.6213,126.4160,"Bitung, Indonesia",NaN,Indonesia
146,"M 6.5 - 166km SSW of Ndoi Island, Fiji",6.5,08-11-2019 10:44,0,2,green,0,650,us,0,4.765,25.00,mww,577.00,-21.9449,-179.5110,"Ndoi Island, Fiji",NaN,NaN
147,"M 6.6 - 136 km W of Neiafu, Tonga",6.6,04-11-2019 22:43,4,4,green,1,673,us,0,5.086,48.00,mww,10.00,-18.5747,-175.2720,"Neiafu, Tonga",NaN,NaN
148,"M 6.5 - 2km ESE of Kisante, Philippines",6.5,31-10-2019 01:11,9,7,green,1,733,us,0,0.428,19.00,mww,10.00,6.9098,125.1780,"Kisante, Philippines",NaN,Philippines
149,"M 6.6 - 10 km NE of Columbio, Philippines",6.6,29-10-2019 01:04,9,7,yellow,1,780,us,0,0.646,24.00,mww,15.00,6.7567,125.0080,"Columbio, Philippines",NaN,Philippines

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
150,"M 6.7 - 70 km WSW of Constitución, Chile",6.7,29-09-2019 15:57,7,6,green,1,844,us,0,1.26900,98.0,mww,11.00,-35.4758,-73.1630,"Constitución, Chile",NaN,NaN
151,"M 6.5 - 11km S of Kairatu, Indonesia",6.5,25-09-2019 23:46,7,7,yellow,1,656,us,0,3.90900,15.0,mww,12.26,-3.4528,128.3700,"Kairatu, Indonesia",NaN,Indonesia
152,"M 6.6 - 34km NNE of Ndoi Island, Fiji",6.6,01-09-2019 15:54,2,3,NaN,1,671,us,0,4.12100,19.0,mww,591.00,-20.3641,-178.5700,"Ndoi Island, Fiji",NaN,Fiji
153,"M 6.6 - 131km S of Bristol Island, South Sandw...",6.6,27-08-2019 23:55,0,4,green,1,670,us,0,12.89600,19.0,mww,16.00,-60.2152,-26.5801,"Bristol Island, South Sandwich Islands",NaN,United Kingdom of Great Britain and Northern I...
154,"M 6.9 - 152 km SW of Labuan, Indonesia",6.9,02-08-2019 12:03,4,6,green,0,875,us,0,2.83900,23.0,mww,49.00,-7.2822,104.7910,"Labuan, Indonesia",NaN,NaN
155,"M 6.8 - 96 km SW of San Antonio, Chile",6.8,01-08-2019 18:28,6,6,green,1,947,us,0,0.81700,35.0,mww,25.00,-34.2364,-72.3102,"San Antonio, Chile",NaN,NaN
156,"M 6.6 - 62km E of Lakatoro, Vanuatu",6.6,31-07-2019 15:02,0,4,green,1,670,us,0,6.02400,30.0,mww,181.00,-16.1985,167.9980,"Lakatoro, Vanuatu",NaN,Vanuatu
157,"M 7.2 - 93km NNE of Laiwui, Indonesia",7.2,14-07-2019 09:10,7,7,green,1,809,us,0,1.50400,38.0,mww,18.98,-0.5858,128.0340,"Laiwui, Indonesia",NaN,Indonesia
158,"M 6.6 - 200km W of Broome, Australia",6.6,14-07-2019 05:39,5,5,green,0,791,us,0,2.97800,32.0,mww,10.00,-18.2242,120.3580,"Broome, Australia",NaN,NaN
159,"M 6.9 - 134km WSW of Kota Ternate, Indonesia",6.9,07-07-2019 15:08,7,5,green,0,747,us,0,1.20500,21.0,mww,35.00,0.5126,126.1890,"Kota Ternate, Indonesia",NaN,Indonesia
160,"M 7.1 - 18km W of Searles Valley, CA",7.1,06-07-2019 03:19,9,9,yellow,0,1646,ci,77,0.04616,43.0,mw,8.00,35.7695,-117.5990,"Searles Valley, CA",North America,United States of America
161,"M 7.3 - 292km NW of Saumlaki, Indonesia",7.3,24-06-2019 02:53,4,6,green,1,952,us,0,2.62900,16.0,mww,212.00,-6.4078,129.1690,"Saumlaki, Indonesia",NaN,Indonesia
162,"M 7.3 - 116km NE of L'Esperance Rock, New Zealand",7.3,15-06-2019 22:55,8,6,green,1,830,us,0,1.40200,11.0,mww,46.00,-30.6441,-178.1000,"L'Esperance Rock, New Zealand",NaN,NaN
163,"M 6.6 - 32 km S of La Libertad, El Salvador",6.6,30-05-2019 09:03,7,6,yellow,1,886,us,0,1.19300,22.0,mww,57.92,13.1994,-89.3056,"La Libertad, El Salvador",NaN,NaN
164,"M 8.0 - 78 km NE of Navarro, Peru",8.0,26-05-2019 07:41,9,8,orange,1,1890,us,0,3.18000,17.0,mww,122.57,-5.8119,-75.2697,"Navarro, Peru",South America,Peru
165,"M 7.6 - 46km SSE of Namatanai, Papua New Guinea",7.6,14-05-2019 12:58,7,7,green,1,929,us,0,0.45300,16.0,mww,10.00,-4.0510,152.5970,"Namatanai, Papua New Guinea",NaN,Papua New Guinea
166,"M 7.1 - 33km NW of Bulolo, Papua New Guinea",7.1,06-05-2019 21:19,7,6,yellow,1,826,us,0,2.51400,16.0,mww,146.00,-6.9746,146.4490,"Bulolo, Papua New Guinea",NaN,Papua New Guinea
167,"M 6.8 - 98km SSW of Luwuk, Indonesia",6.8,12-04-2019 11:40,5,6,green,1,717,us,0,0.79100,28.0,mww,15.46,-1.8146,122.5800,"Luwuk, Indonesia",NaN,Indonesia
168,"M 6.5 - 83km ENE of Bristol Island, South Sand...",6.5,09-04-2019 17:53,0,5,green,1,650,us,0,7.56800,18.0,mww,38.00,-58.6262,-25.3040,"Bristol Island, South Sandwich Islands",NaN,NaN
169,"M 7.0 - 22 km NNE of Azángaro, Peru",7.0,01-03-2019 08:50,7,4,green,1,869,us,0,2.50100,42.0,mww,267.00,-14.7131,-70.1546,"Azángaro, Peru",South America,Peru
170,"M 7.5 - 111km ESE of Palora, Ecuador",7.5,22-02-2019 10:17,7,7,yellow,1,1145,us,0,2.04500,15.0,mww,145.00,-2.1862,-77.0505,"Palora, Ecuador",South America,Ecuador
171,"M 6.7 - 5 km SW of Puerto Madero, Mexico",6.7,01-02-2019 16:14,6,6,yellow,1,909,us,0,0.28900,43.0,mww,66.00,14.6802,-92.4527,"Puerto Madero, Mexico",NaN,Mexico
172,M 6.7 - Prince Edward Islands region,6.7,22-01-2019 19:01,0,3,green,0,691,us,0,7.52700,17.0,mww,13.00,-43.1219,42.3568,Prince Edward Islands region,NaN,NaN
173,"M 6.7 - 10 km SSW of Coquimbo, Chile",6.7,20-01-2019 01:32,8,8,orange,1,1600,us,0,0.17300,22.0,mww,63.00,-30.0404,-71.3815,"Coquimbo, Chile",South America,Chile
174,"M 6.6 - 94 km NW of Sola, Vanuatu",6.6,15-01-2019 18:06,5,4,green,1,671,us,0,7.81800,18.0,mww,35.00,-13.3360,166.8750,"Sola, Vanuatu",NaN,Vanuatu
175,M 6.6 - Molucca Sea,6.6,06-01-2019 17:27,2,4,green,1,672,us,0,1.59600,33.0,mww,43.21,2.2580,126.7580,Molucca Sea,NaN,Indonesia
176,"M 6.8 - 90km W of Tarauaca, Brazil",6.8,05-01-2019 19:25,3,3,green,0,715,us,0,1.18100,16.0,mww,570.41,-8.1440,-71.5870,"Tarauaca, Brazil",South America,Brazil
177,"M 7.0 - 96 km ESE of Pondaguitan, Philippines",7.0,29-12-2018 03:39,5,5,green,1,803,us,0,1.76900,21.0,mww,60.21,5.8983,126.9210,"Pondaguitan, Philippines",NaN,NaN
178,"M 7.3 - 187 km SE of Ust’-Kamchatsk Staryy, Ru...",7.3,20-12-2018 17:01,3,7,green,1,822,us,0,4.12600,23.0,mww,16.56,55.0999,164.6990,"Ust’-Kamchatsk Staryy, Russia",NaN,NaN
179,M 7.1 - South Sandwich Islands region,7.1,11-12-2018 02:26,0,5,green,1,776,us,0,7.04300,20.0,mww,133.00,-58.5446,-26.3856,South Sandwich Islands region,NaN,South Georgia and the South Sandwich Islands
180,"M 6.6 - 199 km ESE of Tadine, New Caledonia",6.6,05-12-2018 06:43,0,4,green,1,670,us,0,2.67900,31.0,mww,10.00,-22.0629,169.7330,"Tadine, New Caledonia",NaN,NaN
181,"M 7.5 - 166 km ESE of Tadine, New Caledonia",7.5,05-12-2018 04:18,3,6,green,1,871,us,0,2.40500,18.0,mww,10.00,-21.9496,169.4270,"Tadine, New Caledonia",NaN,NaN
182,"M 7.1 - 1 km SE of Point MacKenzie, Alaska",7.1,30-11-2018 17:29,8,8,orange,1,1790,ak,0,0.00000,0.0,mw,46.70,61.3464,-149.9550,"Point MacKenzie, Alaska",North America,United States of America
183,"M 6.8 - 187 km E of Levuka, Fiji",6.8,18-11-2018 20:25,0,3,green,1,711,us,0,2.87900,39.0,mww,540.00,-17.8735,-178.9270,"Levuka, Fiji",NaN,Fiji
184,"M 6.7 - 120 km NW of Olonkinbyen, Svalbard and...",6.7,09-11-2018 01:49,3,4,green,1,693,us,0,7.85300,19.0,mww,10.00,71.6312,-11.2431,"Olonkinbyen, Svalbard and Jan Mayen",NaN,NaN
185,"M 6.8 - 32 km SW of Lithakiá, Greece",6.8,25-10-2018 22:54,8,7,yellow,0,954,us,0,2.26800,15.0,mww,14.00,37.5203,20.5565,"Lithakiá, Greece",Europe,NaN
186,"M 6.5 - 237 km SW of Port McNeill, Canada",6.5,22-10-2018 06:22,2,4,green,0,655,us,0,1.69200,68.0,mww,10.00,49.2970,-129.7240,"Port McNeill, Canada",NaN,NaN
187,"M 6.8 - 210 km SW of Port McNeill, Canada",6.8,22-10-2018 06:16,4,4,green,1,776,us,0,1.50500,36.0,mww,10.00,49.3346,-129.2890,"Port McNeill, Canada",NaN,NaN
188,"M 6.5 - 223 km SW of Port McNeill, Canada",6.5,22-10-2018 05:39,3,4,green,1,669,us,0,1.61100,63.0,mww,10.00,49.2586,-129.4120,"Port McNeill, Canada",NaN,NaN
189,"M 6.5 - 171 km E of Tadine, New Caledonia",6.5,16-10-2018 01:03,0,4,green,1,650,us,0,2.10900,22.0,mww,17.00,-21.7427,169.5220,"Tadine, New Caledonia",NaN,NaN
190,"M 6.7 - 269 km WNW of Ozernovskiy, Russia",6.7,13-10-2018 11:10,0,3,green,1,691,us,0,2.70500,17.0,mww,461.00,52.8549,153.2430,"Ozernovskiy, Russia",NaN,NaN
191,"M 6.5 - 154 km S of Severo-Kuril’sk, Russia",6.5,10-10-2018 23:16,0,4,green,1,650,us,0,3.92300,14.0,mww,20.00,49.2902,156.2970,"Severo-Kuril’sk, Russia",NaN,NaN
192,"M 7.0 - 119 km E of Kimbe, Papua New Guinea",7.0,10-10-2018 20:48,6,6,green,1,758,us,0,1.77800,18.0,mww,39.00,-5.7012,151.2050,"Kimbe, Papua New Guinea",NaN,Papua New Guinea
193,"M 6.7 - 279 km E of Levuka, Fiji",6.7,30-09-2018 10:52,2,3,green,1,691,us,0,3.74500,23.0,mww,550.00,-18.3604,-178.0630,"Levuka, Fiji",NaN,Fiji
194,"M 7.5 - 72 km N of Palu, Indonesia",7.5,28-09-2018 10:02,8,8,red,0,2026,us,0,1.64900,13.0,mww,20.00,-0.2559,119.8460,"Palu, Indonesia",NaN,Indonesia
195,M 6.5 - south of the Fiji Islands,6.5,16-09-2018 21:11,4,1,green,0,651,us,0,5.13900,18.0,mww,576.00,-25.4150,178.1990,the Fiji Islands,NaN,NaN
196,M 6.9 - Kermadec Islands region,6.9,10-09-2018 04:19,3,4,green,0,735,us,0,2.78500,18.0,mww,115.00,-31.7447,-179.3730,Kermadec Islands region,NaN,NaN
197,"M 6.5 - 66 km NW of Kirakira, Solomon Islands",6.5,09-09-2018 19:31,3,6,green,1,651,us,0,1.63800,25.0,mww,68.00,-10.0207,161.5030,"Kirakira, Solomon Islands",NaN,Solomon Islands
198,"M 7.9 - 45 km S of Levuka, Fiji",7.9,06-09-2018 15:49,7,4,green,1,979,us,0,1.43100,12.0,mww,670.81,-18.4743,179.3500,"Levuka, Fiji",NaN,Fiji
199,"M 6.6 - 27 km ESE of Chitose, Japan",6.6,05-09-2018 18:07,8,9,orange,1,1075,us,0,1.13000,32.0,mww,35.00,42.6861,141.9290,"Chitose, Japan",Asia,Japan

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
200,"M 7.1 - 238 km ESE of Tadine, New Caledonia",7.1,29-08-2018 03:51,2,5,green,1,776,us,0,2.548,23.0,mww,21.43,-22.0295,170.1260,"Tadine, New Caledonia",NaN,NaN
201,"M 7.1 - 136 km W of Iñapari, Peru",7.1,24-08-2018 09:04,0,3,green,0,776,us,0,3.770,12.0,mww,630.00,-11.0355,-70.8284,"Iñapari, Peru",South America,Peru
202,"M 6.5 - 78 km E of Lakatoro, Vanuatu",6.5,21-08-2018 22:32,6,7,green,1,652,us,0,4.797,10.0,mww,9.00,-16.0315,168.1430,"Lakatoro, Vanuatu",NaN,Vanuatu
203,"M 7.3 - 40 km ENE of Carúpano, Venezuela",7.3,21-08-2018 21:31,8,6,yellow,1,1570,us,0,1.822,15.0,mww,146.82,10.7731,-62.9019,"Carúpano, Venezuela",NaN,Venezuela
204,"M 6.9 - 20 km NNW of Labuan Lombok, Indonesia",6.9,19-08-2018 14:56,7,7,green,0,1206,us,0,2.453,31.0,mww,21.00,-8.3190,116.6270,"Labuan Lombok, Indonesia",NaN,Indonesia
205,"M 8.2 - 267 km E of Levuka, Fiji",8.2,19-08-2018 00:19,5,4,green,1,1050,us,0,3.630,13.0,mww,600.00,-18.1125,-178.1530,"Levuka, Fiji",NaN,Fiji
206,"M 6.5 - 124 km N of Labuan Bajo, Indonesia",6.5,17-08-2018 15:35,5,3,green,0,743,us,0,2.719,23.0,mww,529.00,-7.3718,119.8020,"Labuan Bajo, Indonesia",NaN,Indonesia
207,"M 6.5 - 108 km WSW of Adak, Alaska",6.5,15-08-2018 21:56,6,6,green,1,655,us,0,0.576,22.0,mww,33.93,51.4234,-178.0260,"Adak, Alaska",North America,United States of America
208,"M 6.9 - 36 km NW of Labuan Lombok, Indonesia",6.9,05-08-2018 11:46,9,8,orange,0,1704,us,0,2.271,15.0,mww,34.00,-8.2581,116.4380,"Labuan Lombok, Indonesia",NaN,Indonesia
209,"M 6.9 - 18 km SSW of Leilani Estates, Hawaii",6.9,04-05-2018 22:32,7,8,yellow,1,1392,hv,63,0.110,210.0,mw,5.81,19.3182,-155.0000,"Leilani Estates, Hawaii",NaN,United States of America
210,"M 6.8 - 38 km SE of Boyuibe, Bolivia",6.8,02-04-2018 13:40,5,3,green,0,733,us,0,5.320,16.0,mww,559.00,-20.6588,-63.0058,"Boyuibe, Bolivia",South America,Bolivia
211,"M 6.9 - 150 km E of Kimbe, Papua New Guinea",6.9,29-03-2018 21:25,9,6,green,1,741,us,0,1.487,18.0,mww,35.00,-5.5321,151.5000,"Kimbe, Papua New Guinea",NaN,Papua New Guinea
212,"M 6.7 - 140 km E of Kimbe, Papua New Guinea",6.7,26-03-2018 09:51,5,6,green,1,696,us,0,1.507,15.0,mww,40.00,-5.5024,151.4020,"Kimbe, Papua New Guinea",NaN,Papua New Guinea
213,"M 6.8 - 103 km E of Kokopo, Papua New Guinea",6.8,08-03-2018 17:39,6,6,green,1,719,us,0,1.049,16.0,mww,22.86,-4.3762,153.2000,"Kokopo, Papua New Guinea",NaN,Papua New Guinea
214,"M 6.7 - 62 km SW of Tari, Papua New Guinea",6.7,06-03-2018 14:13,8,7,green,1,697,us,0,5.457,19.0,mww,20.49,-6.3043,142.6120,"Tari, Papua New Guinea",NaN,Papua New Guinea
215,"M 7.5 - 32 km SW of Tari, Papua New Guinea",7.5,25-02-2018 17:44,9,8,yellow,1,943,us,0,5.480,17.0,mww,25.21,-6.0699,142.7540,"Tari, Papua New Guinea",NaN,Papua New Guinea
216,"M 7.2 - 4 km S of Pinotepa de Don Luis, Mexico",7.2,16-02-2018 23:39,7,7,yellow,1,1384,us,0,0.142,82.0,mww,22.00,16.3855,-97.9787,"Pinotepa de Don Luis, Mexico",North America,Mexico
217,"M 7.9 - 261 km SE of Chiniak, Alaska",7.9,23-01-2018 09:31,9,4,green,1,1870,us,0,2.585,30.0,mww,14.06,56.0039,-149.1660,"Chiniak, Alaska",NaN,NaN
218,"M 7.1 - 37 km W of Atiquipa, Peru",7.1,14-01-2018 09:18,9,7,green,1,1075,us,0,4.290,23.0,mww,39.00,-15.7675,-74.7092,"Atiquipa, Peru",NaN,Peru
219,"M 7.5 - 203 km NNE of Barra Patuca, Honduras",7.5,10-01-2018 02:51,8,5,green,1,1623,us,0,4.581,12.0,mww,19.00,17.4825,-83.5200,"Barra Patuca, Honduras",NaN,NaN
220,"M 6.5 - 12 km SSW of Kawalu, Indonesia",6.5,15-12-2017 16:47,8,7,green,0,998,us,0,2.365,28.0,mww,90.00,-7.4921,108.1740,"Kawalu, Indonesia",NaN,Indonesia
221,M 6.5 - Bouvet Island region,6.5,13-12-2017 18:03,1,5,green,1,651,us,0,17.654,23.0,mww,17.00,-54.2189,2.1628,Bouvet Island region,NaN,NaN
222,"M 7.0 - 85 km ENE of Tadine, New Caledonia",7.0,19-11-2017 22:43,4,6,green,1,771,us,0,0.617,14.0,mww,10.00,-21.3246,168.6710,"Tadine, New Caledonia",NaN,NaN
223,"M 6.6 - 74 km E of Tadine, New Caledonia",6.6,19-11-2017 15:09,4,5,green,1,676,us,0,0.529,21.0,mww,13.00,-21.5027,168.5980,"Tadine, New Caledonia",NaN,NaN
224,"M 6.5 - 18 km W of Parrita, Costa Rica",6.5,13-11-2017 02:28,8,8,yellow,1,1153,us,0,0.225,37.0,mww,19.36,9.5147,-84.4865,"Parrita, Costa Rica",NaN,Costa Rica
225,"M 7.3 - 29 km S of ?alabja, Iraq",7.3,12-11-2017 18:18,8,9,red,0,2790,us,0,0.284,33.0,mww,19.00,34.9109,45.9592,"?alabja, Iraq",Asia,Iran
226,"M 6.5 - 67 km WSW of Angoram, Papua New Guinea",6.5,07-11-2017 21:26,6,5,green,1,661,us,0,4.449,10.0,mww,110.57,-4.2433,143.4850,"Angoram, Papua New Guinea",NaN,Papua New Guinea
227,"M 6.8 - 97 km NE of Hihifo, Tonga",6.8,04-11-2017 09:00,5,5,green,1,727,us,0,4.852,21.0,mww,10.00,-15.3197,-173.1680,"Hihifo, Tonga",NaN,NaN
228,"M 6.6 - 101 km E of Tadine, New Caledonia",6.6,01-11-2017 02:23,3,5,green,1,674,us,0,0.788,29.0,mww,22.00,-21.6484,168.8590,"Tadine, New Caledonia",NaN,NaN
229,"M 6.7 - 132 km E of Tadine, New Caledonia",6.7,31-10-2017 00:42,3,4,green,1,691,us,0,1.062,55.0,mww,24.00,-21.6971,169.1480,"Tadine, New Caledonia",NaN,NaN
230,"M 6.7 - 181 km NNE of Maumere, Indonesia",6.7,24-10-2017 10:47,3,3,green,0,694,us,0,1.634,16.0,mww,553.81,-7.2168,123.0740,"Maumere, Indonesia",NaN,Indonesia
231,"M 6.5 - 247 km ESE of Attu Station, Alaska",6.5,08-10-2017 22:34,3,5,green,1,651,us,0,1.154,11.0,mww,119.00,52.3909,176.7690,"Attu Station, Alaska",North America,NaN
232,"M 7.1 - 1 km S of Matzaco, Mexico",7.1,19-09-2017 18:14,9,8,NaN,0,1686,us,0,0.984,23.0,mww,48.00,18.5499,-98.4887,"Matzaco, Mexico",North America,Mexico
233,"M 8.2 - near the coast of Chiapas, Mexico",8.2,08-09-2017 04:49,9,7,red,1,2910,us,0,0.944,22.0,mww,47.39,15.0222,-93.8993,"Chiapas, Mexico",NaN,NaN
234,"M 6.5 - 168 km SW of Mawu, China",6.5,08-08-2017 13:19,5,7,yellow,0,707,us,0,11.411,22.0,mww,9.00,33.1926,103.8550,"Mawu, China",Asia,People's Republic of China
235,"M 6.6 - 11 km ENE of Kos, Greece",6.6,20-07-2017 22:31,7,7,yellow,0,1064,us,0,0.913,16.0,mww,7.00,36.9293,27.4139,"Kos, Greece",Asia,Turkey
236,"M 7.7 - Komandorskiye Ostrova, Russia region",7.7,17-07-2017 23:34,8,7,green,1,918,us,0,3.564,13.0,mww,10.00,54.4434,168.8570,"Komandorskiye Ostrova, Russia region",NaN,NaN
237,"M 6.6 - Auckland Islands, New Zealand region",6.6,11-07-2017 07:00,5,4,green,1,704,us,0,3.773,37.0,mww,10.00,-49.4837,164.0160,"Auckland Islands, New Zealand region",NaN,NaN
238,"M 6.5 - 2 km S of Lim-oo, Philippines",6.5,06-07-2017 08:03,9,8,yellow,1,740,us,0,4.139,30.0,mww,9.00,11.1269,124.6290,"Lim-oo, Philippines",NaN,Philippines
239,"M 6.8 - 28 km SW of Puerto San José, Guatemala",6.8,22-06-2017 12:31,6,6,yellow,1,1034,us,0,1.065,38.0,mww,38.12,13.7174,-90.9718,"Puerto San José, Guatemala",NaN,NaN
240,"M 6.9 - 2 km SSW of San Pablo, Guatemala",6.9,14-06-2017 07:29,8,6,yellow,1,1188,us,0,0.247,35.0,mww,93.00,14.9091,-92.0092,"San Pablo, Guatemala",NaN,Guatemala
241,"M 6.8 - 200 km NW of Attu Station, Alaska",6.8,02-06-2017 22:24,0,4,green,1,711,us,0,2.308,12.0,mww,5.00,54.0312,170.9200,"Attu Station, Alaska",NaN,NaN
242,"M 6.6 - 37 km WNW of Poso, Indonesia",6.6,29-05-2017 14:35,7,7,green,0,678,us,0,2.353,18.0,mww,12.00,-1.2923,120.4310,"Poso, Indonesia",NaN,Indonesia
243,M 6.5 - South Sandwich Islands region,6.5,10-05-2017 23:23,0,4,green,1,650,us,0,6.489,17.0,mww,15.00,-56.4140,-25.7432,South Sandwich Islands region,NaN,NaN
244,"M 6.8 - 59 km NNE of Port-Olry, Vanuatu",6.8,09-05-2017 13:52,6,5,green,1,713,us,0,7.495,19.0,mww,169.00,-14.5884,167.3770,"Port-Olry, Vanuatu",NaN,Vanuatu
245,"M 6.9 - 31 km SW of Burias, Philippines",6.9,28-04-2017 20:23,9,6,green,1,814,us,0,1.636,14.0,mww,26.00,5.5043,125.0660,"Burias, Philippines",NaN,Philippines
246,"M 6.9 - 40 km W of Valparaíso, Chile",6.9,24-04-2017 21:38,9,7,yellow,1,1642,us,0,0.356,39.0,mww,28.00,-33.0375,-72.0617,"Valparaíso, Chile",NaN,NaN
247,"M 6.5 - 132 km WSW of Moijabana, Botswana",6.5,03-04-2017 17:40,7,8,green,0,1297,us,0,2.360,15.0,mww,29.00,-22.6784,25.1558,"Moijabana, Botswana",Africa,Botswana
248,"M 6.6 - 81 km NNE of Ust’-Kamchatsk Staryy, Ru...",6.6,29-03-2017 04:09,6,7,yellow,1,671,us,0,4.591,14.0,mww,17.00,56.9401,162.7860,"Ust’-Kamchatsk Staryy, Russia",Asia,Russia
249,M 6.9 - south of the Fiji Islands,6.9,24-02-2017 17:28,2,3,green,1,733,us,0,6.012,19.0,mww,414.50,-23.2593,-178.8040,the Fiji Islands,NaN,NaN

In [ ]:
eq_data = pd.read_csv("data/earthquake_data.csv")
eq_data

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 7.0 - 18 km SW of Malango, Solomon Islands",7.0,22-11-2022 02:03,8,7,green,1,768,us,117,0.5090,17.0,mww,14.000,-9.7963,159.596,"Malango, Solomon Islands",Oceania,Solomon Islands
8,"M 6.8 - 55 km SSW of Aguililla, Mexico",6.8,22-09-2022 06:16,8,7,yellow,1,1179,us,175,2.1370,92.0,mww,20.000,18.3300,-102.913,"Aguililla, Mexico",North America,Mexico
9,"M 7.6 - 35 km SSW of Aguililla, Mexico",7.6,19-09-2022 18:05,9,8,yellow,1,1799,us,271,1.1530,69.0,mww,26.943,18.3667,-103.252,"Aguililla, Mexico",North America,Mexico
10,"M 6.9 - 90 km E of Yujing, Taiwan",6.9,18-09-2022 06:44,9,9,yellow,1,887,us,215,0.4010,34.0,mww,10.000,23.1444,121.307,"Yujing, Taiwan",Asia,Taiwan
11,"M 6.5 - 96 km SE of Lugu, Taiwan",6.5,17-09-2022 13:41,7,7,green,1,756,us,178,0.4300,54.0,mww,10.000,23.0290,121.348,"Lugu, Taiwan",Asia,Taiwan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
406,"M 6.6 - 183 km SW of Belaya Gora, Russia",6.6,14-02-2013 13:13,0,7,green,1,670,us,697,0.0000,15.3,mww,11.000,67.6310,142.508,"Belaya Gora, Russia",Asia,Russia
408,"M 6.9 - 2 km NNE of Yacuanquer, Colombia",6.9,09-02-2013 14:16,5,5,green,1,904,us,562,0.0000,23.7,mww,145.000,1.1350,-77.393,"Yacuanquer, Colombia",South America,Colombia
415,"M 6.9 - 18 km SSW of Obihiro, Japan",6.9,02-02-2013 14:17,6,7,yellow,0,814,us,686,0.0000,28.0,mww,107.000,42.7700,143.092,"Obihiro, Japan",Asia,Japan
416,"M 6.8 - 54 km N of Vallenar, Chile",6.8,30-01-2013 20:15,6,7,green,0,771,us,596,0.0000,19.3,mww,45.000,-28.0940,-70.653,"Vallenar, Chile",South America,Chile
507,"M 7.2 - 12km SW of Delta, B.C., MX",7.2,04-04-2010 22:40,9,9,red,0,2910,ci,10,0.5137,239.0,mw,9.987,32.2862,-115.295,"Delta, B.C., MX",North America,Mexico